const sqlite3=require('sqlite3').verbose();
const crypto=require('crypto');
function hashPassword(password){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `scrypt$${salt}$${hash}`;}
function verifyPassword(password,stored){if(!stored)return false;if(!stored.startsWith('scrypt$'))return String(password)===stored;const [,salt,hash]=stored.split('$');try{const actual=crypto.scryptSync(String(password),salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(actual,'hex'),Buffer.from(hash,'hex'));}catch{return false;}}
class Database{
 constructor(file){this.file=file;this.db=new sqlite3.Database(file);this.init();}
 run(sql,p=[]){return new Promise((res,rej)=>this.db.run(sql,p,function(e){e?rej(e):res({lastID:this.lastID,changes:this.changes});}));}
 get(sql,p=[]){return new Promise((res,rej)=>this.db.get(sql,p,(e,r)=>e?rej(e):res(r)));}
 all(sql,p=[]){return new Promise((res,rej)=>this.db.all(sql,p,(e,r)=>e?rej(e):res(r||[])));}
 async init(){
  await this.run('PRAGMA foreign_keys=ON');
  await this.run(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('doctor','center')),active INTEGER DEFAULT 1)`);
  await this.run(`CREATE TABLE IF NOT EXISTS patients(id INTEGER PRIMARY KEY AUTOINCREMENT,file_no TEXT UNIQUE NOT NULL,full_name TEXT NOT NULL,phone TEXT,birth_date TEXT,gender TEXT,address TEXT,diagnosis TEXT,chief_complaint TEXT,initial_assessment TEXT,treatment_plan TEXT,allergies TEXT,contraindications TEXT,previous_surgery TEXT,red_flags TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,status TEXT DEFAULT 'active')`);
  await this.run(`CREATE TABLE IF NOT EXISTS appointments(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,appointment_date TEXT NOT NULL,status TEXT DEFAULT 'scheduled',notes TEXT,FOREIGN KEY(patient_id) REFERENCES patients(id))`);
  await this.run(`CREATE TABLE IF NOT EXISTS treatment_plans(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,total_sessions INTEGER DEFAULT 0,completed_sessions INTEGER DEFAULT 0,session_price REAL DEFAULT 0,start_date TEXT,status TEXT DEFAULT 'active',FOREIGN KEY(patient_id) REFERENCES patients(id))`);
  await this.run(`CREATE TABLE IF NOT EXISTS sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,session_no INTEGER NOT NULL,session_date TEXT NOT NULL,therapist TEXT,status_today TEXT,what_was_done TEXT,exercises TEXT,response TEXT,result TEXT,notes TEXT,next_plan TEXT,FOREIGN KEY(patient_id) REFERENCES patients(id))`);
  await this.run(`CREATE TABLE IF NOT EXISTS home_exercises(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,exercise_name TEXT NOT NULL,sets TEXT,reps TEXT,duration TEXT,frequency TEXT,notes TEXT,active INTEGER DEFAULT 1,FOREIGN KEY(patient_id) REFERENCES patients(id))`);
  await this.run(`CREATE TABLE IF NOT EXISTS feedback(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,session_id INTEGER,therapist_rating INTEGER,appointment_rating INTEGER,explanation_rating INTEGER,service_rating INTEGER,reception_rating INTEGER,cleanliness_rating INTEGER,comment TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(patient_id) REFERENCES patients(id))`);
  await this.run(`CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,patient_id INTEGER NOT NULL,amount REAL NOT NULL,payment_date TEXT DEFAULT CURRENT_TIMESTAMP,notes TEXT,FOREIGN KEY(patient_id) REFERENCES patients(id))`);
  await this.run(`CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,amount REAL NOT NULL,expense_date TEXT DEFAULT CURRENT_TIMESTAMP,category TEXT,notes TEXT)`);
  await this.run(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT)`);
  await this.run(`CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,action TEXT NOT NULL,entity TEXT,entity_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
  await this.run(`INSERT OR IGNORE INTO users(username,password,role) VALUES('doctor','1234','doctor'),('center','1234','center')`);
  await this.run(`INSERT OR IGNORE INTO settings(key,value) VALUES('clinic_name','Physio Center'),('default_session_price','0'),('currency','جنيه')`);
 }
 async login(u,p){try{const row=await this.get('SELECT id,username,password,role,active FROM users WHERE username=?',[u]);if(!row||!row.active||!verifyPassword(p,row.password))return{ok:false,message:'اسم المستخدم أو كلمة المرور غير صحيحة'};if(!row.password.startsWith('scrypt$'))await this.run('UPDATE users SET password=? WHERE id=?',[hashPassword(p),row.id]);return{ok:true,user:{id:row.id,username:row.username,role:row.role}};}catch(e){return{ok:false,message:e.message}}}
 async audit(uid,a,e,id){try{await this.run('INSERT INTO audit_logs(user_id,action,entity,entity_id) VALUES(?,?,?,?)',[uid,a,e,id]);}catch(_) {}}
 async dashboard(role){try{const d=await this.get(`SELECT (SELECT COUNT(*) FROM patients WHERE status='active') patients,(SELECT COUNT(*) FROM appointments WHERE date(appointment_date,'localtime')=date('now','localtime')) todayAppointments,(SELECT COUNT(*) FROM sessions WHERE date(session_date)=date('now','localtime')) todaySessions,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE date(payment_date,'localtime')=date('now','localtime')) todayRevenue,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE strftime('%Y-%m',payment_date,'localtime')=strftime('%Y-%m','now','localtime')) monthRevenue,(SELECT COALESCE(SUM(amount),0) FROM expenses WHERE strftime('%Y-%m',expense_date,'localtime')=strftime('%Y-%m','now','localtime')) monthExpenses`);if(role!=='doctor'){d.todayRevenue=null;d.monthRevenue=null;d.monthExpenses=null;}return{ok:true,data:d};}catch(e){return{ok:false,message:e.message}}}
 async listPatients(q=''){return this.all(`SELECT id,file_no,full_name,phone,diagnosis,status,created_at FROM patients WHERE full_name LIKE ? OR file_no LIKE ? OR phone LIKE ? ORDER BY id DESC`,[`%${q}%`,`%${q}%`,`%${q}%`]);}
 async addPatient(p,uid){try{const r=await this.get('SELECT COALESCE(MAX(id),0)+1 n FROM patients');const no=String(r.n).padStart(5,'0');const x=await this.run(`INSERT INTO patients(file_no,full_name,phone,birth_date,gender,address,diagnosis,chief_complaint,initial_assessment,treatment_plan,allergies,contraindications,previous_surgery,red_flags) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[no,p.full_name,p.phone,p.birth_date,p.gender,p.address,p.diagnosis,p.chief_complaint,p.initial_assessment,p.treatment_plan,p.allergies,p.contraindications,p.previous_surgery,p.red_flags]);await this.audit(uid,'create','patient',x.lastID);return{ok:true,id:x.lastID,file_no:no};}catch(e){return{ok:false,message:e.message}}}
 async getPatient(id){return this.get('SELECT * FROM patients WHERE id=?',[id]);}
 async updatePatient(id,p,uid){try{await this.run(`UPDATE patients SET full_name=?,phone=?,birth_date=?,gender=?,address=?,diagnosis=?,chief_complaint=?,initial_assessment=?,treatment_plan=?,allergies=?,contraindications=?,previous_surgery=?,red_flags=? WHERE id=?`,[p.full_name,p.phone,p.birth_date,p.gender,p.address,p.diagnosis,p.chief_complaint,p.initial_assessment,p.treatment_plan,p.allergies,p.contraindications,p.previous_surgery,p.red_flags,id]);await this.audit(uid,'update','patient',id);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async listAppointments(date){return this.all(`SELECT a.*,p.file_no,p.full_name,p.phone FROM appointments a JOIN patients p ON p.id=a.patient_id WHERE date(a.appointment_date)=date(?) ORDER BY a.appointment_date`,[date]);}
 async addAppointment(d,uid){try{const x=await this.run('INSERT INTO appointments(patient_id,appointment_date,status,notes) VALUES(?,?,?,?)',[d.patient_id,d.appointment_date,'scheduled',d.notes||'']);await this.audit(uid,'create','appointment',x.lastID);return{ok:true,id:x.lastID};}catch(e){return{ok:false,message:e.message}}}
 async updateAppointmentStatus(id,status,uid){try{await this.run('UPDATE appointments SET status=? WHERE id=?',[status,id]);await this.audit(uid,'status','appointment',id);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async getTreatmentPlans(id){return this.all('SELECT * FROM treatment_plans WHERE patient_id=? ORDER BY id DESC',[id]);}
 async addTreatmentPlan(d,uid){try{const x=await this.run('INSERT INTO treatment_plans(patient_id,total_sessions,session_price,start_date) VALUES(?,?,?,?)',[d.patient_id,Number(d.total_sessions)||0,Number(d.session_price)||0,d.start_date||new Date().toISOString().slice(0,10)]);await this.audit(uid,'create','treatment_plan',x.lastID);return{ok:true,id:x.lastID};}catch(e){return{ok:false,message:e.message}}}
 async getSessions(id){return this.all('SELECT * FROM sessions WHERE patient_id=? ORDER BY session_no DESC',[id]);}
 async addSession(d,uid){try{const x=await this.run('INSERT INTO sessions(patient_id,session_no,session_date,therapist,status_today,what_was_done,exercises,response,result,notes,next_plan) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[d.patient_id,d.session_no,d.session_date,d.therapist,d.status_today,d.what_was_done,d.exercises,d.response,d.result,d.notes,d.next_plan]);await this.run('UPDATE treatment_plans SET completed_sessions=MIN(total_sessions,completed_sessions+1) WHERE patient_id=? AND status="active"',[d.patient_id]);await this.audit(uid,'create','session',x.lastID);return{ok:true,id:x.lastID};}catch(e){return{ok:false,message:e.message}}}
 async getHomeExercises(id){return this.all('SELECT * FROM home_exercises WHERE patient_id=? AND active=1 ORDER BY id DESC',[id]);}
 async addHomeExercise(d,uid){try{const x=await this.run('INSERT INTO home_exercises(patient_id,exercise_name,sets,reps,duration,frequency,notes) VALUES(?,?,?,?,?,?,?)',[d.patient_id,d.exercise_name,d.sets,d.reps,d.duration,d.frequency,d.notes]);await this.audit(uid,'create','home_exercise',x.lastID);return{ok:true,id:x.lastID};}catch(e){return{ok:false,message:e.message}}}
 async addFeedback(d,uid){try{const x=await this.run('INSERT INTO feedback(patient_id,session_id,therapist_rating,appointment_rating,explanation_rating,service_rating,reception_rating,cleanliness_rating,comment) VALUES(?,?,?,?,?,?,?,?,?)',[d.patient_id,d.session_id||null,d.therapist_rating,d.appointment_rating,d.explanation_rating,d.service_rating,d.reception_rating,d.cleanliness_rating,d.comment]);await this.audit(uid,'create','feedback',x.lastID);return{ok:true,id:x.lastID};}catch(e){return{ok:false,message:e.message}}}
 async getFeedback(){return this.all(`SELECT f.*,p.full_name,p.file_no FROM feedback f JOIN patients p ON p.id=f.patient_id ORDER BY f.id DESC`);}
 async getFinancialSummary(){const r=await this.get(`SELECT (SELECT COALESCE(SUM(amount),0) FROM payments WHERE date(payment_date,'localtime')=date('now','localtime')) today,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE strftime('%Y-%m',payment_date,'localtime')=strftime('%Y-%m','now','localtime')) month,(SELECT COALESCE(SUM(amount),0) FROM expenses WHERE strftime('%Y-%m',expense_date,'localtime')=strftime('%Y-%m','now','localtime')) expenses`);r.profit=r.month-r.expenses;return{ok:true,data:r};}
 async addPayment(d,uid){try{const x=await this.run('INSERT INTO payments(patient_id,amount,notes) VALUES(?,?,?)',[d.patient_id,Number(d.amount),d.notes]);await this.audit(uid,'create','payment',x.lastID);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async addExpense(d,uid){try{const x=await this.run('INSERT INTO expenses(amount,category,notes) VALUES(?,?,?)',[Number(d.amount),d.category,d.notes]);await this.audit(uid,'create','expense',x.lastID);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async getReports(range={}){try{const from=range.from||new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);const to=range.to||new Date().toISOString().slice(0,10);const x=await this.get(`SELECT (SELECT COUNT(*) FROM patients WHERE status='active') patients,(SELECT COUNT(*) FROM sessions WHERE date(session_date) BETWEEN date(?) AND date(?)) sessions,(SELECT COUNT(*) FROM appointments WHERE date(appointment_date) BETWEEN date(?) AND date(?) AND status='attended') attended,(SELECT COUNT(*) FROM appointments WHERE date(appointment_date) BETWEEN date(?) AND date(?) AND status='absent') absent,(SELECT COALESCE(SUM(amount),0) FROM payments WHERE date(payment_date,'localtime') BETWEEN date(?) AND date(?)) revenue,(SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(expense_date,'localtime') BETWEEN date(?) AND date(?)) expenses`,[from,to,from,to,from,to,from,to,from,to]);x.profit=x.revenue-x.expenses;x.from=from;x.to=to;return{ok:true,data:x};}catch(e){return{ok:false,message:e.message}}} 
 async getFeedbackSummary(){try{const x=await this.get(`SELECT COUNT(*) count,ROUND(AVG(therapist_rating),2) therapist,ROUND(AVG(appointment_rating),2) appointment,ROUND(AVG(explanation_rating),2) explanation,ROUND(AVG(service_rating),2) service,ROUND(AVG(reception_rating),2) reception,ROUND(AVG(cleanliness_rating),2) cleanliness,ROUND((AVG(therapist_rating)+AVG(appointment_rating)+AVG(explanation_rating)+AVG(service_rating)+AVG(reception_rating)+AVG(cleanliness_rating))/6,2) overall FROM feedback`);return{ok:true,data:x};}catch(e){return{ok:false,message:e.message}}}
 async getSettings(){const rows=await this.all('SELECT key,value FROM settings');return{ok:true,data:Object.fromEntries(rows.map(x=>[x.key,x.value]))};}
 async saveSettings(d,uid){try{for(const [k,v] of Object.entries(d))await this.run('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',[k,String(v)]);await this.audit(uid,'update','settings',null);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async listUsers(){return this.all('SELECT id,username,role,active FROM users ORDER BY id');}
 async addUser(d,uid){try{const username=String(d.username||'').trim();const password=String(d.password||'');if(!username||password.length<4)return{ok:false,message:'اسم المستخدم مطلوب وكلمة المرور يجب ألا تقل عن 4 أحرف'};if(!['doctor','center'].includes(d.role))return{ok:false,message:'الدور غير صالح'};const x=await this.run('INSERT INTO users(username,password,role) VALUES(?,?,?)',[username,hashPassword(password),d.role]);await this.audit(uid,'create','user',x.lastID);return{ok:true};}catch(e){return{ok:false,message:e.message.includes('UNIQUE')?'اسم المستخدم موجود بالفعل':e.message}}}
 async changePassword(id,newPassword,uid){try{if(!newPassword||String(newPassword).length<4)return{ok:false,message:'كلمة المرور يجب ألا تقل عن 4 أحرف'};if(Number(id)!==Number(uid))return{ok:false,message:'يمكنك تغيير كلمة مرور حسابك فقط من هذه الشاشة'};await this.run('UPDATE users SET password=? WHERE id=?',[hashPassword(newPassword),id]);await this.audit(uid,'change_password','user',id);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async toggleUser(id,uid){try{if(Number(id)===Number(uid))return{ok:false,message:'لا يمكن تعطيل حسابك الحالي'};const target=await this.get('SELECT id,role,active FROM users WHERE id=?',[id]);if(!target)return{ok:false,message:'المستخدم غير موجود'};if(target.active===1&&target.role==='doctor'){const c=await this.get("SELECT COUNT(*) n FROM users WHERE role='doctor' AND active=1");if(Number(c.n)<=1)return{ok:false,message:'يجب أن يظل هناك دكتور واحد نشط على الأقل'};}await this.run('UPDATE users SET active=CASE active WHEN 1 THEN 0 ELSE 1 END WHERE id=?',[id]);await this.audit(uid,'toggle','user',id);return{ok:true};}catch(e){return{ok:false,message:e.message}}}
 async getAuditLogs(){return this.all(`SELECT a.*,u.username FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 500`);}
 close(){return new Promise((res,rej)=>this.db.close(e=>e?rej(e):res()));}
}
module.exports=Database;
